# Generated by Django 6.0.6 on 2026-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Phone', models.CharField(max_length=11, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
