# Generated by Django 6.0.6 on 2026-07-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyT', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default='unknown', max_length=255, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='https://img.magnific.com/premium-photo/flatlay-various-electronic-gadgets-devices-white-surface-including-laptops-smartphones-cameras-more_14117-594521.jpg', max_length=255, upload_to='products/'),
            preserve_default=False,
        ),
    ]
